"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8081";
type Guest={id:string;name:string;token?:string;selection:string[];matchId?:string;queued:boolean};
type Definition={id:string;name:string;MaxHP:number;MoveRange:number;MoveCost:number;AttackRange:number;AttackPower:number;AttackCost:number};
type Position={x:number;y:number};
type Fighter={id:string;definitionId:string;ownerId:string;name:string;HP:number;MaxHP:number;position:Position};
type Player={id:string;name:string;cost:number};
type Match={matchId:string;revision:number;players:[Player,Player];characters:Fighter[];turnPlayerId:string;turn:number;winnerId?:string;finished:boolean;lastEvent:{type:string;text:string}};

async function request<T>(path:string, options:RequestInit={}, token=""):Promise<T>{
  const response=await fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}) ,...options.headers}});
  const body=await response.json(); if(!response.ok) throw new Error(body.error??"通信に失敗しました"); return body;
}
const commandId=()=>crypto.randomUUID();

export default function Home(){
  const [token,setToken]=useState(""); const [guest,setGuest]=useState<Guest|null>(null); const [definitions,setDefinitions]=useState<Definition[]>([]); const [match,setMatch]=useState<Match|null>(null);
  const [name,setName]=useState(""); const [selected,setSelected]=useState<string[]>(["vanguard","ranger"]); const [actor,setActor]=useState(""); const [mode,setMode]=useState<"move"|"attack">("move"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const loadMe=useCallback(async(t:string)=>{const me=await request<Guest>("/api/me",{},t);setGuest(me);setSelected(me.selection);return me},[]);
  const loadMatch=useCallback(async(id:string,t=token)=>{const state=await request<Match>(`/api/matches/${id}`,{},t);setMatch(state);return state},[token]);
  useEffect(()=>{async function bootstrap(){request<Definition[]>("/api/characters").then(setDefinitions).catch(e=>setError(e.message));const saved=localStorage.getItem("auxilia-token");if(!saved)return;try{const me=await loadMe(saved);setToken(saved);if(me.matchId)await loadMatch(me.matchId,saved)}catch{localStorage.removeItem("auxilia-token")}}void bootstrap()},[loadMe,loadMatch]);
  useEffect(()=>{if(!token||!guest?.queued)return;const timer=setInterval(()=>loadMe(token).then(me=>me.matchId&&loadMatch(me.matchId,token)).catch(e=>setError(e.message)),1000);return()=>clearInterval(timer)},[guest?.queued,loadMatch,loadMe,token]);
  const matchID=match?.matchId; const matchFinished=match?.finished;
  useEffect(()=>{if(!token||!matchID||matchFinished)return;const timer=setInterval(()=>loadMatch(matchID).catch(()=>{}),900);return()=>clearInterval(timer)},[loadMatch,matchID,matchFinished,token]);
  const me=match?.players.find(p=>p.id===guest?.id); const opponent=match?.players.find(p=>p.id!==guest?.id); const myTurn=match?.turnPlayerId===guest?.id;
  const active=useMemo(()=>match?.characters.find(c=>c.id===actor),[actor,match]);
  async function join(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const joined=await request<Guest>("/api/guests",{method:"POST",body:JSON.stringify({name})});setToken(joined.token!);localStorage.setItem("auxilia-token",joined.token!);setGuest(joined);setSelected(joined.selection)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function saveSelection(){setBusy(true);setError("");try{const next=await request<Guest>("/api/me/selection",{method:"PUT",body:JSON.stringify({characterIds:selected})},token);setGuest(next)}catch(e){setError((e as Error).message);throw e}finally{setBusy(false)}}
  async function queue(){try{await saveSelection();setBusy(true);setGuest(await request<Guest>("/api/matchmaking",{method:"POST",body:"{}"},token))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function cancel(){setGuest(await request<Guest>("/api/matchmaking",{method:"DELETE"},token))}
  function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(v=>v!==id):current.length<2?[...current,id]:[current[1],id])}
  async function act(position:Position){if(!match||!actor||!myTurn)return;setError("");setBusy(true);try{const path=mode==="move"?"move":"attack";const next=await request<Match>(`/api/matches/${match.matchId}/${path}`,{method:"POST",body:JSON.stringify({commandId:commandId(),expectedRevision:match.revision,characterId:actor,target:position})},token);setMatch(next);setActor("")}catch(e){setError((e as Error).message);await loadMatch(match.matchId)}finally{setBusy(false)}}
  async function endTurn(){if(!match)return;setBusy(true);try{setMatch(await request<Match>(`/api/matches/${match.matchId}/end-turn`,{method:"POST",body:JSON.stringify({commandId:commandId(),expectedRevision:match.revision,characterId:"",target:{x:0,y:0}})},token));setActor("")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function reset(){localStorage.removeItem("auxilia-token");location.reload()}

  if(match?.finished){const winner=match.players.find(p=>p.id===match.winnerId);return <Frame step="RESULT"><section className="result"><p className="eyebrow">MATCH COMPLETE</p><div className="result-mark">{winner?.id===guest?.id?"WIN":"LOSE"}</div><h1>{winner?.name} の勝利</h1><p>{match.turn}ターン・最終リビジョン {match.revision}</p><button className="primary" onClick={reset}>エントランスへ戻る</button></section></Frame>}
  if(match&&guest){return <Frame step={`MATCH ${match.matchId.slice(-6).toUpperCase()}`}><section className="battle-head"><div><span>TURN {match.turn}</span><h2>{myTurn?"あなたのターン":"相手のターン"}</h2></div><div className="score"><b>{me?.name}</b><span>COST {me?.cost}</span><i>VS</i><b>{opponent?.name}</b><span>COST {opponent?.cost}</span></div><button disabled={!myTurn||busy} onClick={endTurn}>ターン終了</button></section><section className="battle-layout"><div className="board">{Array.from({length:40},(_,i)=>{const p={x:i%8,y:Math.floor(i/8)};const fighter=match.characters.find(c=>c.HP>0&&c.position.x===p.x&&c.position.y===p.y);const mine=fighter?.ownerId===guest.id;return <button key={i} aria-label={`グリッド ${p.x},${p.y}`} className={`${fighter?"occupied":""} ${mine?"mine":"enemy"} ${actor===fighter?.id?"active":""}`} onClick={()=>fighter&&mine?setActor(fighter.id):act(p)}><small>{p.x},{p.y}</small>{fighter&&<><strong>{fighter.name.slice(0,2)}</strong><em>{fighter.HP}</em></>}</button>})}</div><aside className="battle-panel"><p className="eyebrow">ACTION CONTROL</p><h3>{active?.name??"キャラクターを選択"}</h3><div className="mode"><button className={mode==="move"?"on":""} onClick={()=>setMode("move")}>移動</button><button className={mode==="attack"?"on":""} onClick={()=>setMode("attack")}>攻撃</button></div><p>{active?`${mode==="move"?"移動先":"攻撃対象"}のマスを選んでください。判定はサーバーで行われます。`:"自分のユニットを選択してください。"}</p><div className="event"><span>LATEST EVENT</span>{match.lastEvent.text}</div>{error&&<p className="error">{error}</p>}</aside></section></Frame>}
  if(guest){return <Frame step="ENTRANCE"><section className="entrance-head"><div><p className="eyebrow">WELCOME, {guest.name.toUpperCase()}</p><h1>部隊を編成する。</h1></div><div className={`status ${guest.queued?"searching":""}`}>{guest.queued?"対戦相手を検索中":"2体を選択"}</div></section><section className="cards">{definitions.map((d,index)=><button key={d.id} className={`character ${selected.includes(d.id)?"selected":""}`} onClick={()=>!guest.queued&&toggle(d.id)}><span>0{index+1}</span><h2>{d.name}</h2><div className="silhouette">{d.name.slice(0,1)}</div><dl><div><dt>HP</dt><dd>{d.MaxHP}</dd></div><div><dt>MOVE</dt><dd>{d.MoveRange}</dd></div><div><dt>ATK</dt><dd>{d.AttackPower}</dd></div><div><dt>RANGE</dt><dd>{d.AttackRange}</dd></div></dl></button>)}</section><section className="match-bar"><div><b>{selected.length}/2 SELECTED</b><span>{guest.queued?"マッチ成立後、自動でゲーム画面に移動します":"異なるキャラクターを2体選んでください"}</span></div>{guest.queued?<button className="secondary" onClick={cancel}>キャンセル</button>:<button className="primary" disabled={selected.length!==2||busy} onClick={queue}>マッチング開始</button>}</section>{error&&<p className="floating-error">{error}</p>}</Frame>}
  return <Frame step="GUEST ENTRY"><section className="welcome"><p className="eyebrow">TACTICAL ONLINE BATTLE</p><h1>戦場に、<br/>名前を刻め。</h1><p className="lead">登録不要。名前を決めたら、すぐに戦術グリッドへ。</p><form onSubmit={join} className="join-card"><label htmlFor="player-name">プレイヤー名</label><div className="join-row"><input id="player-name" value={name} onChange={e=>setName(e.target.value)} maxLength={20} placeholder="名前を入力" autoComplete="nickname"/><button disabled={busy}>エントランスへ</button></div><small>1〜20文字・アカウント登録は必要ありません</small></form>{error&&<p className="error">{error}</p>}</section><aside className="grid-preview">{Array.from({length:40},(_,i)=><span key={i} className={i===9||i===26?"unit":i===14?"target":""}/>)}</aside></Frame>
}

function Frame({step,children}:{step:string;children:React.ReactNode}){return <main className="app"><header className="brand"><b>AUXILIA</b><span>Battle Prototype</span><i>{step}</i></header>{children}<footer>SERVER AUTHORITATIVE · 5 × 8 GRID · TURN BASED</footer></main>}
